version: '2'

services:
   db:
     image: mysql:5.7
     volumes:
       - ./db:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_DATABASE: best
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     volumes:
       - ./bestmotives:/var/www/html
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_NAME: best
       WORDPRESS_DB_PASSWORD: wordpress
   phpmtadmin:
      depends_on: 
        - db
      image: phpmyadmin/phpmyadmin
      ports: 
        - "8080:80"
      restart: always
      environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=db:3306
        - PMA_USER=root
        - PMA_PASSWORD=wordpress
      